# Generated by Django 6.0.3 on 2026-03-05 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_limite', models.DateField()),
                ('horario_limite', models.TimeField(blank=True, default='23:59', null=True)),
                ('status', models.CharField(default='Pendente', max_length=100)),
                ('dias_para_execucao', models.IntegerField(default=1)),
                ('data_comeco', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.categoria')),
            ],
        ),
    ]
