# Generated by Django 6.0.3 on 2026-03-10 03:48

import tarefas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_comeco',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='dias_para_execucao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_execucao',
            field=models.DateField(blank=True, null=True, verbose_name='Quando deseja começar a fazer a tarefa? (opcional)'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_limite',
            field=models.DateField(validators=[tarefas.models.validar_data_limite]),
        ),
    ]
