# Generated by Django 6.0.3 on 2026-03-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_remove_tarefa_data_comeco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_execucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
